### ISSUE TITLE
Should Solr be assumed?

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp-recipe-core#1]
https://github.com/silverstripe/cwp-recipe-core/blob/8018af1192c1ca852b6b0e8ace8201d798e928da/mysite/_config/environmentcheck.yml#L9

Should this configuration option be at least with a new section, with the header option
```yml
Only:
  moduleexists: FulltextSearch
```
Or is it a graceful fail / handled inside the php code?

**Comment by robbieaverill** [comment]
No, it shouldn't. @raissanorth is patching this now

**Comment by NightJar** [comment]
Nice, great work team! :D
