### ISSUE TITLE
Recipe should enforce the public webroot

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-recipe-core#10]
CWP 2.0 via the cwp-installer does enforce a public webroot but this recipe on its own doesn't - it should =)

**Comment by robbieaverill** [comment]
@tractorcow if I add an empty file into `public/` in this repository, will that mean that a public web root is always created when using this recipe on its own?

**Comment by tractorcow** [comment]
Yes, but only if the recipe is used as root.

**Comment by robbieaverill** [comment]
This needs to be done in cwp-recipe-cms as well, because recipe-cms is installed before cwp-recipe-core is (see issue: https://github.com/silverstripe/recipe-plugin/issues/12) so the public folder is created too late.

**Comment by robbieaverill** [comment]
Fixed with https://github.com/silverstripe/cwp-recipe-core/commit/ca0f7ed60adb8e13c596d0ba4610d966f1527f8b and https://github.com/silverstripe/cwp-recipe-cms/commit/bbe633fbbb6d8abead13f396d3f41a5946ac5308
